import { randomUUID } from "node:crypto";
import type { Conversation, Database, KnowledgeGap } from "./domain";
import { performanceReport } from "./closure";

export type ReportFilters = { from: string; to: string; channel?: string; language?: string; category?: string; product?: string; resolutionStatus?: string; ticketStatus?: string };
export function filteredReport(database: Database, tenantId: string, filters: ReportFilters) { if (!filters.from || !filters.to) throw new Error("Date range is required."); const from=new Date(`${filters.from}T00:00:00.000Z`).getTime(),to=new Date(`${filters.to}T23:59:59.999Z`).getTime(); if(!Number.isFinite(from)||!Number.isFinite(to)||from>to) throw new Error("Date range is invalid."); const ticketByConversation=new Map(database.tickets.filter(item=>item.tenantId===tenantId).map(item=>[item.conversationId,item])); const conversations=database.conversations.filter(item=>item.tenantId===tenantId&&new Date(item.createdAt).getTime()>=from&&new Date(item.createdAt).getTime()<=to&&(!filters.channel||(item.channel??"CHAT")===filters.channel)&&(!filters.language||item.language===filters.language)&&(!filters.category||item.classification.category===filters.category)&&(!filters.product||item.issue.model.toLowerCase().includes(filters.product.toLowerCase()))&&(!filters.resolutionStatus||item.status===filters.resolutionStatus)&&(!filters.ticketStatus||ticketByConversation.get(item.id)?.status===filters.ticketStatus)); const ids=new Set(conversations.map(item=>item.id)); const scoped:Database={...database,conversations,conversationFeedback:database.conversationFeedback.filter(item=>ids.has(item.conversationId)),tickets:database.tickets.filter(item=>item.tenantId===tenantId&&ids.has(item.conversationId))}; return { ...performanceReport(scoped,tenantId), conversations }; }
const csvCell=(value:unknown)=>`"${String(value??"").replaceAll('"','""')}"`;
export function reportCsv(conversations: Conversation[]) { return ["Created,Channel,Language,Category,Product,Status,Summary",...conversations.map(item=>[item.createdAt,item.channel??"CHAT",item.language,item.classification.category,item.issue.model,item.status,item.issue.summary].map(csvCell).join(","))].join("\r\n"); }
export function refreshKnowledgeGaps(database: Database, tenantId: string, now=new Date().toISOString()) { database.knowledgeGaps??=[]; const candidates=database.conversations.filter(item=>item.tenantId===tenantId&&(Boolean(item.lowConfidenceReason)||["TICKET_CREATED","ESCALATED_WITHOUT_TICKET","FAILED"].includes(item.status))); for(const item of candidates){ const normalized=item.issue.summary.toLowerCase().replace(/[^a-z0-9 ]/g," ").split(/\s+/).filter(Boolean).slice(0,6).join(" ")||item.classification.category.toLowerCase(); let gap=database.knowledgeGaps.find(existing=>existing.tenantId===tenantId&&existing.normalizedSummary===normalized&&existing.status==="OPEN"); if(!gap){ gap={id:randomUUID(),tenantId,category:item.classification.category,normalizedSummary:normalized,conversationIds:[],reasons:[],status:"OPEN",reviewedBy:null,createdAt:now,updatedAt:now}; database.knowledgeGaps.push(gap); } if(!gap.conversationIds.includes(item.id))gap.conversationIds.push(item.id); const reason=item.lowConfidenceReason?"LOW_CONFIDENCE":"UNRESOLVED"; if(!gap.reasons.includes(reason))gap.reasons.push(reason); gap.updatedAt=now; } return database.knowledgeGaps.filter(item=>item.tenantId===tenantId); }
export function reviewKnowledgeGap(database:Database,tenantId:string,gapId:string,actorId:string,now=new Date().toISOString()):KnowledgeGap { const gap=(database.knowledgeGaps??[]).find(item=>item.id===gapId&&item.tenantId===tenantId); if(!gap)throw new Error("Knowledge gap not found."); gap.status="REVIEWED"; gap.reviewedBy=actorId; gap.updatedAt=now; return gap; }
export function filterAuditLogs(database:Database,tenantId:string,filters:{actor?:string;action?:string;entity?:string;from?:string;to?:string}) { return database.auditLogs.filter(item=>item.tenantId===tenantId&&(!filters.actor||item.actorUserId.includes(filters.actor))&&(!filters.action||item.action.toLowerCase().includes(filters.action.toLowerCase()))&&(!filters.entity||item.entityType.toLowerCase().includes(filters.entity.toLowerCase()))&&(!filters.from||item.createdAt>=`${filters.from}T00:00:00.000Z`)&&(!filters.to||item.createdAt<=`${filters.to}T23:59:59.999Z`)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)); }
