import { POST as chatPost } from "@/app/api/chat/route";
import { mutateDatabase, readDatabase } from "@/lib/store";
import { activeWhatsAppConversation, claimMessage, languageForMessage, MetaWhatsAppAdapter, parseTenantMap, parseWhatsAppMessages, verifyWhatsAppSignature } from "@/lib/whatsapp";

export async function GET(request:Request){const url=new URL(request.url);const mode=url.searchParams.get("hub.mode"),token=url.searchParams.get("hub.verify_token"),challenge=url.searchParams.get("hub.challenge");if(mode==="subscribe"&&token&&token===process.env.WHATSAPP_VERIFY_TOKEN&&challenge)return new Response(challenge,{status:200});return new Response("Forbidden",{status:403})}

export async function POST(request:Request){const rawBody=await request.text();if(!verifyWhatsAppSignature(rawBody,request.headers.get("x-hub-signature-256")))return Response.json({error:"Invalid WhatsApp signature."},{status:401});let payload:unknown;try{payload=JSON.parse(rawBody)}catch{return Response.json({error:"Invalid JSON body."},{status:400})}const messages=parseWhatsAppMessages(payload);const tenantMap=parseTenantMap();const adapter=new MetaWhatsAppAdapter();
  for(const inbound of messages){const tenantSlug=tenantMap[inbound.phoneNumberId];if(!tenantSlug)continue;const snapshot=await readDatabase();const tenant=snapshot.tenants.find(item=>item.slug===tenantSlug&&item.status==="ACTIVE");if(!tenant)continue;let receiptId:string|null=null;await mutateDatabase(database=>{const receipt=claimMessage(database,tenant.id,inbound);receiptId=receipt?.id??null});if(!receiptId)continue;
    try{const current=activeWhatsAppConversation(await readDatabase(),tenant.id,inbound.senderId);const language=current?.language??languageForMessage(tenant,inbound.text);const chatRequest=new Request("http://internal/api/chat",{method:"POST",headers:{"content-type":"application/json","x-forwarded-for":`whatsapp:${inbound.senderId}`},body:JSON.stringify({tenantSlug:tenant.slug,language,action:current?"reply":"start",conversationId:current?.id,message:inbound.text,channel:"WHATSAPP",contact:{name:inbound.senderName,email:`${inbound.senderId}@whatsapp.invalid`,equipmentId:"Not provided",whatsappNumber:inbound.senderId}})});const response=await chatPost(chatRequest);const result=await response.json() as {conversationId?:string;reply?:string;error?:string;ticketReference?:string};if(!response.ok)throw new Error(result.error??"Support workflow rejected the message.");if(!result.conversationId||!result.reply)throw new Error("Support workflow returned an incomplete response.");await mutateDatabase(database=>{const conversation=database.conversations.find(item=>item.id===result.conversationId&&item.tenantId===tenant.id);if(conversation)conversation.channel="WHATSAPP";const receipt=database.messagingReceipts?.find(item=>item.id===receiptId&&item.tenantId===tenant.id);if(receipt){receipt.conversationId=result.conversationId;receipt.status="PROCESSED";receipt.updatedAt=new Date().toISOString()}});const branded=`${tenant.branding.supportAgentName}: ${result.reply}${result.ticketReference?`\n\nTicket: ${result.ticketReference}`:""}`;await adapter.sendText(inbound.phoneNumberId,inbound.senderId,branded)}catch(error){await mutateDatabase(database=>{const receipt=database.messagingReceipts?.find(item=>item.id===receiptId&&item.tenantId===tenant.id);if(receipt){receipt.status="FAILED";receipt.error=error instanceof Error?error.message:"Messaging failed.";receipt.updatedAt=new Date().toISOString()}});return Response.json({error:"WhatsApp message processing failed."},{status:500})}}
  return Response.json({received:true});
}
