import { requireUser } from "@/lib/auth";
import { assertCan, scopeTenant } from "@/lib/rbac";
import { getTenantTicketing, readDatabase } from "@/lib/store";
import { configureTicketStatusSync, pullTicketStatus } from "./actions";

export default async function TicketSyncPage({ searchParams }: { searchParams: Promise<{ tenantId?: string }> }) {
  const actor = await requireUser(); assertCan(actor.role, "integrations:manage"); const database = await readDatabase(); const tenantId = scopeTenant(actor.role, actor.tenantId, (await searchParams).tenantId ?? (actor.role === "SUPER_ADMIN" ? database.tenants[0]?.id : undefined)); const data = await getTenantTicketing(tenantId);
  return <main className="content"><a href="/admin">← Admin</a><h1>Two-way ticket status sync</h1><p className="muted">Receive signed provider webhooks or securely poll configured status endpoints. External status never bypasses user resolution confirmation.</p><section className="panel"><h3>Status endpoint configuration</h3>{data.integrations.map((integration) => <form className="form-grid" action={configureTicketStatusSync} key={integration.id}><input type="hidden" name="integrationId" value={integration.id} /><label className="field">Integration<input value={integration.name} readOnly /></label><label className="field">Status field path<input name="statusFieldPath" defaultValue={integration.statusFieldPath ?? (integration.type === "SERVICENOW" ? "result.state" : "status")} required /></label><label className="field wide">HTTPS status endpoint<input type="url" name="statusEndpointUrl" defaultValue={integration.statusEndpointUrl ?? ""} placeholder="https://provider.example/tickets/{externalId}" required /></label><button className="primary wide">Save status sync configuration</button></form>)}</section><section className="panel"><h3>External ticket statuses</h3>{data.tickets.filter((ticket) => ticket.status === "CREATED").map((ticket) => { const integration = data.integrations.find((item) => item.id === ticket.integrationId); return <div className="user-row" key={ticket.id}><span><b>{ticket.reference}</b><br /><span className="muted">External ID {ticket.externalTicketId ?? "—"} · Status {ticket.externalStatus ?? "Not synchronized"}{ticket.lastStatusSyncedAt ? ` · ${new Date(ticket.lastStatusSyncedAt).toLocaleString()}` : ""}</span></span>{integration?.statusEndpointUrl && <form action={pullTicketStatus}><input type="hidden" name="ticketId" value={ticket.id} /><button>Pull status</button></form>}</div>; })}</section><section className="panel"><h3>Recent status sync activity</h3>{data.syncLogs.filter((item) => item.action === "STATUS_PULL" || item.action === "STATUS_WEBHOOK").slice(0, 30).map((item) => <div className="audit-row" key={item.id}><span><b>{item.action}</b><br /><span className="muted">{item.status}{item.errorMessage ? ` · ${item.errorMessage}` : ""}</span></span><time>{new Date(item.createdAt).toLocaleString()}</time></div>)}</section></main>;
}
