"use client";

import { FormEvent, useState } from "react";
import type { SupportedLanguage, Tenant } from "@/lib/domain";

type ChatMessage = { role: "agent" | "user"; content: string };
type ChatPayload = { error?: string; conversationId?: string; reply?: string; status?: string; ticketReference?: string; requestFeedback?: boolean; feedbackSubmitted?: boolean };
const terminalStatuses = new Set(["RESOLVED", "TICKET_CREATED", "ESCALATED_WITHOUT_TICKET", "ABANDONED", "FAILED"]);
const labels = {
  en: { greeting: "Before troubleshooting, I’ll collect a few details and check for safety risks.", name: "Your name", email: "Work email", equipmentId: "Equipment or asset ID", site: "Site or location", issue: "Describe what is happening, including any error code", start: "Send issue", followup: "Add the requested details", send: "Send", safety: "If anyone is in immediate danger, contact local emergency services now." },
  hi: { greeting: "समस्या निवारण से पहले मैं कुछ विवरण लूँगी और सुरक्षा जोखिम जाँचूँगी।", name: "आपका नाम", email: "कार्य ईमेल", equipmentId: "उपकरण या एसेट आईडी", site: "साइट या स्थान", issue: "समस्या और त्रुटि कोड का विवरण दें", start: "समस्या भेजें", followup: "माँगी गई जानकारी जोड़ें", send: "भेजें", safety: "यदि कोई तत्काल खतरे में है तो स्थानीय आपातकालीन सेवाओं से अभी संपर्क करें।" },
  hinglish: { greeting: "Troubleshooting se pehle main kuch details collect karke safety risk check karungi.", name: "Aapka naam", email: "Work email", equipmentId: "Equipment ya asset ID", site: "Site ya location", issue: "Issue aur error code detail mein batayein", start: "Issue bhejein", followup: "Requested details add karein", send: "Send", safety: "Agar koi immediate danger mein hai, local emergency services ko abhi contact karein." },
};

export function ChatClient({ tenant }: { tenant: Tenant }) {
  const [language, setLanguage] = useState<SupportedLanguage>(tenant.settings.defaultLanguage);
  const [conversationId, setConversationId] = useState(""); const [messages, setMessages] = useState<ChatMessage[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [status, setStatus] = useState(""); const [feedbackRequested, setFeedbackRequested] = useState(false); const [feedbackSubmitted, setFeedbackSubmitted] = useState(false); const t = labels[language];

  async function send(body: Record<string, unknown>) {
    setBusy(true); setError("");
    try { const response = await fetch("/api/chat", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ tenantSlug: tenant.slug, language, conversationId, ...body }) }); const payload = await response.json() as ChatPayload; if (!response.ok) throw new Error(payload.error ?? "Unable to continue."); setConversationId(payload.conversationId ?? conversationId); setStatus(payload.status ?? status); setFeedbackRequested(Boolean(payload.requestFeedback) || feedbackRequested); setFeedbackSubmitted(Boolean(payload.feedbackSubmitted) || feedbackSubmitted); const reply = `${payload.reply ?? ""}${payload.ticketReference ? `\n\nTicket reference: ${payload.ticketReference}` : ""}`; if (reply) setMessages((items) => [...items, { role: "agent", content: reply }]); return true; } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to continue."); return false; } finally { setBusy(false); }
  }

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); const message = String(form.get("message") ?? ""); const contact = Object.fromEntries(["name", "email", "equipmentId", "site"].map((key) => [key, String(form.get(key) ?? "")])); setMessages((items) => [...items, { role: "user", content: message }]); const action = !conversationId ? "start" : status === "AWAITING_CONFIRMATION" ? "start_sop" : status === "SOP_IN_PROGRESS" ? "sop_step" : "reply"; if (await send({ action, contact, message, confirmed: action === "sop_step" })) event.currentTarget.reset();
  }

  async function resolve(resolved: boolean) { setMessages((items) => [...items, { role: "user", content: resolved ? "Yes, the issue is resolved." : "No, the issue is not resolved." }]); await send({ action: "resolution_confirmation", resolved }); }
  async function feedback(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); await send({ action: "feedback", rating: Number(form.get("rating")), message: String(form.get("comment") ?? "") }); }

  const final = terminalStatuses.has(status);
  return <div className="chat-app"><aside className="chat-aside"><span className="eyebrow">{tenant.branding.companyDisplayName}</span><h1>Technical support,<br/><em>without the guesswork.</em></h1><p>{t.greeting}</p><div className="safety-note">⚠ {t.safety}</div></aside><section className="chat-window"><header><span className="avatar">{tenant.branding.supportAgentName.slice(0,1)}</span><div><b>{tenant.branding.supportAgentName}</b><small>{tenant.branding.productDisplayName} · Online</small></div><select aria-label="Language" value={language} onChange={(event)=>setLanguage(event.target.value as SupportedLanguage)} disabled={Boolean(conversationId)}>{tenant.settings.enabledLanguages.map((item)=><option key={item} value={item}>{item === "en" ? "English" : item === "hi" ? "हिन्दी" : "Hinglish"}</option>)}</select></header><div className="chat-scroll"><div className="bubble agent">Hi, I’m {tenant.branding.supportAgentName}, your {tenant.branding.companyDisplayName} support assistant. {t.greeting}</div>{messages.map((item,index)=><div key={index} className={`bubble ${item.role}`}>{item.content}</div>)}{status === "AWAITING_CONFIRMATION" && <div className="status-chip">Summary confirmation required</div>}{status === "SOP_IN_PROGRESS" && <div className="status-chip">Approved SOP in progress</div>}{status === "AWAITING_RESOLUTION_CONFIRMATION" && <div className="status-chip">Resolution confirmation required</div>}{["TICKET_CREATED","ESCALATED_WITHOUT_TICKET"].includes(status) && <div className="status-chip danger">Escalated for human support</div>}{status === "RESOLVED" && <div className="status-chip success">Session resolved</div>}</div>
  {status === "AWAITING_RESOLUTION_CONFIRMATION" ? <div className="resolution-panel"><b>Is your issue fully resolved?</b><div><button disabled={busy} className="primary" onClick={()=>resolve(true)}>Yes, resolved</button><button disabled={busy} onClick={()=>resolve(false)}>No, escalate</button></div>{error&&<p className="error">{error}</p>}</div> : feedbackRequested && !feedbackSubmitted ? <form onSubmit={feedback} className="feedback-form"><b>How was your support experience?</b><div className="rating-row">{[5,4,3,2,1].map(value=><label key={value}><input type="radio" name="rating" value={value} required/> {value} ★</label>)}</div><textarea name="comment" rows={2} placeholder="Optional comment"/><button className="primary" disabled={busy}>Submit feedback</button>{error&&<p className="error">{error}</p>}</form> : feedbackSubmitted ? <div className="resolution-panel"><b>Thank you for your feedback.</b></div> : !final ? <form onSubmit={submit} className="chat-form">{!conversationId && <div className="contact-grid"><label>{t.name}<input name="name" required={tenant.settings.requiredSupportFields.includes("name")}/></label><label>{t.email}<input name="email" type="email" required={tenant.settings.requiredSupportFields.includes("email")}/></label><label>{t.equipmentId}<input name="equipmentId" required={tenant.settings.requiredSupportFields.includes("equipmentId")}/></label><label>{t.site}<input name="site" required={tenant.settings.requiredSupportFields.includes("site")}/></label></div>}<label>{status === "AWAITING_CONFIRMATION" ? "Confirm the summary to start an approved SOP" : status === "SOP_IN_PROGRESS" ? "Enter your response and confirm this step" : conversationId ? t.followup : t.issue}<textarea name="message" required rows={3}/></label>{error && <p className="error">{error}</p>}<button className="primary" disabled={busy}>{busy ? "…" : status === "AWAITING_CONFIRMATION" ? "Confirm and start SOP" : status === "SOP_IN_PROGRESS" ? "Confirm step" : conversationId ? t.send : t.start}</button></form> : null}<footer>{tenant.branding.privacyPolicyUrl && <a href={tenant.branding.privacyPolicyUrl}>Privacy</a>}{tenant.branding.termsUrl && <a href={tenant.branding.termsUrl}>Terms</a>}{!tenant.branding.hidePlatformBranding && <span>Powered by ResolveOps</span>}</footer></section></div>;
}
