import { requireUser } from "@/lib/auth";
import { assertCan, scopeTenant } from "@/lib/rbac";
import { readDatabase } from "@/lib/store";
import { convertCandidate, dismissCandidate } from "./actions";

export default async function KnowledgeCandidatesPage({ searchParams }: { searchParams: Promise<{ tenantId?: string }> }) {
  const actor = await requireUser(); assertCan(actor.role, "knowledge:manage"); const database = await readDatabase(); const tenantId = scopeTenant(actor.role, actor.tenantId, (await searchParams).tenantId ?? (actor.role === "SUPER_ADMIN" ? database.tenants[0]?.id : undefined)); const candidates = (database.knowledgeCandidates ?? []).filter((item) => item.tenantId === tenantId).sort((a, b) => b.createdAt.localeCompare(a.createdAt));
  return <main className="content"><a href="/admin">← Admin</a><h1>Resolved-ticket KB candidates</h1><p className="muted">Only externally resolved tickets appear here. Converting creates a draft; it remains unavailable to live support until a Knowledge Manager separately approves its document version.</p><section className="panel"><h3>Pending review</h3>{candidates.filter((item) => item.status === "PENDING").map((candidate) => <article className="knowledge-row" key={candidate.id}><div><b>{candidate.title}</b><span className="knowledge-status draft">PENDING</span><small>Source {candidate.sourceTicketReference} · {candidate.category}</small></div><pre className="candidate-preview">{candidate.proposedContent}</pre><div className="knowledge-actions"><form action={convertCandidate}><input type="hidden" name="candidateId" value={candidate.id} /><button>Convert to draft document</button></form><form action={dismissCandidate}><input type="hidden" name="candidateId" value={candidate.id} /><button>Dismiss</button></form></div></article>)}{!candidates.some((item) => item.status === "PENDING") && <p className="muted">No pending candidates.</p>}</section><section className="panel"><h3>Review history</h3>{candidates.filter((item) => item.status !== "PENDING").map((candidate) => <div className="user-row" key={candidate.id}><span><b>{candidate.title}</b><br /><span className="muted">{candidate.sourceTicketReference} · {candidate.status}{candidate.linkedDocumentId ? " · Draft created" : ""}</span></span><time>{new Date(candidate.updatedAt).toLocaleString()}</time></div>)}</section></main>;
}
