/* eslint-disable @next/next/no-img-element */
import { activateSop, createSop, createTenant, addUser, approveKnowledgeVersion, archiveKnowledgeDocument, deactivateUser, logout, saveWebhookIntegration, testWebhookIntegration, updateBranding, updateSettings, uploadKnowledgeDocument, uploadKnowledgeVersion } from "../actions";
import { requireUser } from "@/lib/auth";
import { can } from "@/lib/rbac";
import { getTenantTicketing, listTenantAuditLogs, listTenantKnowledge, listTenantSops, listTenantUsers, readDatabase } from "@/lib/store";
import { roles } from "@/lib/domain";
import { performanceReport } from "@/lib/closure";
import { AdminIdentity, ThemeEditor } from "./theme-editor";

const input = (name: string, label: string, value: string, type = "text") => <div className="field"><label htmlFor={name}>{label}</label><input id={name} name={name} type={type} defaultValue={value} required /></div>;
const issueCategories = ["Mechanical","Electrical","Instrumentation","PLC/Automation","Hydraulic","Pneumatic","Calibration","Installation","Warranty","Spare Parts","Documentation","Preventive Maintenance","Safety","Other"];

export default async function AdminPage({ searchParams }: { searchParams: Promise<{ tenant?: string }> }) {
  const actor = await requireUser(); const database = await readDatabase(); const requested = (await searchParams).tenant;
  const tenant = actor.role === "SUPER_ADMIN" ? database.tenants.find((item) => item.id === requested) ?? database.tenants[0] : database.tenants.find((item) => item.id === actor.tenantId);
  const users = tenant ? await listTenantUsers(tenant.id) : []; const audits = tenant ? await listTenantAuditLogs(tenant.id) : []; const knowledge = tenant ? await listTenantKnowledge(tenant.id) : []; const sops = tenant ? await listTenantSops(tenant.id) : []; const ticketing = tenant ? await getTenantTicketing(tenant.id) : { integrations: [], tickets: [], syncLogs: [] }; const report = tenant ? performanceReport(database, tenant.id) : null;
  return <main className="admin-shell" style={tenant ? { "--color-primary": tenant.theme.primary } as React.CSSProperties : undefined}>{tenant&&<AdminIdentity productName={tenant.branding.productDisplayName}/>}<aside className="sidebar"><h2>{tenant?.branding.logoUrl&&<img className="admin-logo" src={tenant.branding.logoUrl} alt=""/>}{tenant?.branding.hidePlatformBranding?tenant.branding.companyDisplayName:"ResolveOps"}</h2><a href="#overview">Overview</a>{can(actor.role,"reports:read")&&<a href="/admin/reports">Filtered reports</a>}<a href="#settings">Tenant settings</a><a href="#brand">Brand & theme</a><a href="#knowledge">Knowledge base</a>{can(actor.role,"knowledge:manage")&&<a href="/admin/knowledge-gaps">Knowledge gaps</a>}<a href="#sops">SOP engine</a>{can(actor.role,"integrations:manage")&&<a href="/admin/integrations">Native ticketing</a>}<a href="#users">People & roles</a>{can(actor.role,"audit:read")&&<a href="/admin/audit">Search audit logs</a>}</aside><section className="content"><header className="topbar"><div><span className="eyebrow">{actor.role==="SUPER_ADMIN"?"RESOLVEOPS · ADMIN CONTROL CENTRE":"ADMIN CONTROL CENTRE"}</span><h1>{tenant?.branding.companyDisplayName ?? tenant?.name ?? "Platform"}</h1></div><form action={logout}><button>Sign out</button></form></header>
  {actor.role === "SUPER_ADMIN" && <section className="panel"><h3>Create tenant</h3><form action={createTenant} className="form-grid">{input("name","Organization name","")}{input("slug","Tenant URL slug","")}<button className="primary wide">Create tenant</button></form></section>}
  {tenant && report && <><section id="overview" className="stats"><article className="stat"><span className="muted">Total sessions</span><b>{report.totalSessions}</b></article><article className="stat"><span className="muted">Resolution rate</span><b>{Math.round(report.resolutionRate*100)}%</b></article><article className="stat"><span className="muted">Escalation rate</span><b>{Math.round(report.escalationRate*100)}%</b></article><article className="stat"><span className="muted">Average CSAT</span><b>{report.averageCsat===null?"—":report.averageCsat.toFixed(1)}</b></article></section>{can(actor.role,"reports:read")&&<section id="reports" className="panel report-panel"><div><span className="eyebrow">TENANT PERFORMANCE</span><h3>Support outcomes</h3></div><div className="report-grid"><article><span>Resolved sessions</span><b>{report.resolvedSessions}</b></article><article><span>Escalated sessions</span><b>{report.escalatedSessions}</b></article><article><span>Tickets created</span><b>{report.ticketsCreated}</b></article><article><span>Negative feedback</span><b>{report.negativeFeedback}</b></article></div><h4>Top issue categories</h4><div className="category-list">{report.topCategories.length?report.topCategories.map(item=><div key={item.category}><span>{item.category}</span><b>{item.count}</b></div>):<span className="muted">No session data yet.</span>}</div></section>}<div className="grid-two">
  {can(actor.role,"settings:manage") && <><section id="settings" className="panel"><h3>Support behavior</h3><form action={updateSettings}><input type="hidden" name="tenantId" value={tenant.id}/>{input("timezone","Timezone",tenant.settings.timezone)}<div className="field"><label>Default language</label><select name="defaultLanguage" defaultValue={tenant.settings.defaultLanguage}><option value="en">English</option><option value="hi">Hindi</option><option value="hinglish">Hinglish</option></select></div><div className="field"><label>Enabled languages</label><label><input type="checkbox" name="enabledLanguages" value="en" defaultChecked={tenant.settings.enabledLanguages.includes("en")}/> English</label><label><input type="checkbox" name="enabledLanguages" value="hi" defaultChecked={tenant.settings.enabledLanguages.includes("hi")}/> Hindi</label><label><input type="checkbox" name="enabledLanguages" value="hinglish" defaultChecked={tenant.settings.enabledLanguages.includes("hinglish")}/> Hinglish</label></div>{input("requiredSupportFields","Required fields (comma separated)",tenant.settings.requiredSupportFields.join(", "))}{input("confidenceThreshold","AI confidence threshold",String(tenant.settings.confidenceThreshold),"number")}<div className="field"><label>Escalation behavior</label><select name="escalationBehavior" defaultValue={tenant.settings.escalationBehavior}><option value="always">Always</option><option value="outside-hours">Outside hours</option><option value="safety-and-low-confidence">Safety and low confidence</option></select></div><button className="primary">Save support settings</button></form></section>
  <section id="brand" className="panel"><h3>Brand identity</h3><form action={updateBranding}><input type="hidden" name="tenantId" value={tenant.id}/>{input("productDisplayName","Product display name",tenant.branding.productDisplayName)}{input("companyDisplayName","Company display name",tenant.branding.companyDisplayName)}{input("supportAgentName","Support agent name",tenant.branding.supportAgentName)}{input("logoUrl","Logo URL",tenant.branding.logoUrl)}{input("faviconUrl","Favicon URL",tenant.branding.faviconUrl)}{input("footerText","Footer text",tenant.branding.footerText)}{input("supportEmail","Support email",tenant.branding.supportEmail,"email")}{input("supportPhone","Support phone",tenant.branding.supportPhone)}{input("privacyPolicyUrl","Privacy policy URL",tenant.branding.privacyPolicyUrl)}{input("termsUrl","Terms URL",tenant.branding.termsUrl)}<label><input type="checkbox" name="hidePlatformBranding" defaultChecked={tenant.branding.hidePlatformBranding}/> Hide platform branding</label><br/><br/><button className="primary">Save brand</button></form></section>
  <ThemeEditor tenantId={tenant.id} initial={tenant.theme}/></>}
  {can(actor.role,"knowledge:manage") && <section id="knowledge" className="panel"><h3>Approved knowledge</h3><p className="muted">Only an approved active version can be retrieved by live support.</p><form action={uploadKnowledgeDocument} className="form-grid"><input type="hidden" name="tenantId" value={tenant.id}/>{input("title","Document title","")}{input("tags","Tags (comma separated)","")}{input("description","Description","")}<div className="field"><label>PDF, DOCX, TXT, MD or HTML</label><input type="file" name="file" accept=".pdf,.docx,.txt,.md,.html" required/></div><button className="primary wide">Upload as draft</button></form>{knowledge.map(({document,versions})=><article className="knowledge-row" key={document.id}><div><b>{document.title}</b><span className={`knowledge-status ${document.status.toLowerCase()}`}>{document.status}</span><small>{versions.length} version{versions.length===1?"":"s"} · {document.tags.join(", ")||"No tags"}</small></div><div className="knowledge-actions">{versions.filter(version=>version.status==="DRAFT").map(version=><form action={approveKnowledgeVersion} key={version.id}><input type="hidden" name="versionId" value={version.id}/><button>Approve v{version.version}</button></form>)}{document.status!=="ARCHIVED"&&<form action={archiveKnowledgeDocument}><input type="hidden" name="documentId" value={document.id}/><button>Archive</button></form>}</div>{document.status!=="ARCHIVED"&&<form action={uploadKnowledgeVersion} className="version-upload"><input type="hidden" name="documentId" value={document.id}/><input type="file" name="file" accept=".pdf,.docx,.txt,.md,.html" required/><button>Upload new version</button></form>}</article>)}</section>}
  {can(actor.role,"sops:manage") && <section id="sops" className="panel"><h3>Approved SOP engine</h3><p className="muted">Draft ordered flows, mark safety warnings mandatory, then activate only reviewed versions.</p><form action={createSop} className="form-grid"><input type="hidden" name="tenantId" value={tenant.id}/>{input("title","SOP title","")}{input("product","Product or model (optional)","")}<div className="field"><label>Category</label><select name="category">{issueCategories.map(item=><option key={item}>{item}</option>)}</select></div><div className="field"><label>Language</label><select name="language"><option value="en">English</option><option value="hi">Hindi</option><option value="hinglish">Hinglish</option></select></div><div className="field wide"><label>Ordered steps (JSON)</label><textarea name="steps" rows={9} required defaultValue={'[\n  {"id":"safe","type":"safety_warning","content":"Isolate power before inspection.","responseFormat":"boolean","mandatory":true},\n  {"id":"inspect","type":"instruction","content":"Inspect the approved area and report the indicator state.","responseFormat":"text","mandatory":false},\n  {"id":"finish","type":"resolve","content":"Verify normal operation.","responseFormat":"boolean","mandatory":false}\n]'}/></div><button className="primary wide">Create draft SOP</button></form>{sops.map(sop=><article className="knowledge-row" key={sop.id}><div><b>{sop.title}</b><span className={`knowledge-status ${sop.status.toLowerCase()}`}>{sop.status}</span><small>{sop.category} · {sop.language} · v{sop.version} · {sop.steps.length} ordered steps</small></div><div className="knowledge-actions">{sop.status==="DRAFT"&&<form action={activateSop}><input type="hidden" name="sopId" value={sop.id}/><button>Approve & activate</button></form>}</div></article>)}</section>}
  {can(actor.role,"integrations:manage") && <section id="ticketing" className="panel"><h3>Custom webhook ticketing</h3><p className="muted">Credentials are encrypted; audit logs never contain authentication secrets.</p><form action={saveWebhookIntegration} className="form-grid"><input type="hidden" name="tenantId" value={tenant.id}/>{input("name","Integration name","")}{input("endpointUrl","HTTPS endpoint URL","")}<div className="field"><label>Authentication</label><select name="authType"><option value="NONE">None</option><option value="BEARER">Bearer token</option><option value="BASIC">Basic authentication</option></select></div><div className="field"><label>Bearer token</label><input name="token" type="password"/></div><div className="field"><label>Basic username</label><input name="username"/></div><div className="field"><label>Basic password</label><input name="password" type="password"/></div><div className="field wide"><label>Additional headers (JSON)</label><textarea name="headers" rows={3} defaultValue="{}"/></div><div className="field wide"><label>Field mapping: outbound field to normalized path (JSON)</label><textarea name="fieldMapping" rows={5} defaultValue={'{\n  "summary": "issue.summary",\n  "priority": "issue.severity",\n  "requester": "requester.email"\n}'}/></div><button className="primary wide">Save active integration</button></form>{ticketing.integrations.map(integration=><div className="user-row" key={integration.id}><span><b>{integration.name}</b><br/><span className="muted">{integration.endpointUrl} · {integration.lastTestStatus??"Not tested"}</span></span><form action={testWebhookIntegration}><input type="hidden" name="integrationId" value={integration.id}/><button>Send test</button></form></div>)}<h4>Recent tickets</h4>{ticketing.tickets.slice(0,5).map(ticket=><div className="user-row" key={ticket.id}><span><b>{ticket.reference}</b><br/><span className="muted">{ticket.normalizedPayload.issue.summary}</span></span><span className={`knowledge-status ${ticket.status==="CREATED"?"active":""}`}>{ticket.status}</span></div>)}</section>}
  {can(actor.role,"users:manage") && <section id="users" className="panel"><h3>People & roles</h3><form action={addUser} className="form-grid"><input type="hidden" name="tenantId" value={tenant.id}/>{input("name","Name","")}{input("email","Email","","email")}{input("password","Temporary password","","password")}<div className="field"><label>Role</label><select name="role">{roles.filter(r=>r!=="SUPER_ADMIN").map(r=><option key={r}>{r}</option>)}</select></div><button className="primary wide">Add user</button></form>{users.map(user=><div className="user-row" key={user.id}><span><b>{user.name}</b><br/><span className="muted">{user.email} · {user.role}</span></span>{user.status === "ACTIVE" && user.id!==actor.id && <form action={deactivateUser}><input type="hidden" name="userId" value={user.id}/><button>Deactivate</button></form>}</div>)}</section>}
  {can(actor.role,"audit:read") && <section id="audit" className="panel"><h3>Read-only audit trail</h3>{audits.slice(0,10).map(item=><div className="audit-row" key={item.id}><span><b>{item.action}</b><br/><span className="muted">{item.entityType} · {item.actorUserId}</span></span><time>{new Date(item.createdAt).toLocaleString()}</time></div>)}</section>}
  </div></>}</section></main>;
}
