import { createTenant, addUser, approveKnowledgeVersion, archiveKnowledgeDocument, deactivateUser, logout, updateBranding, updateSettings, updateTheme, uploadKnowledgeDocument, uploadKnowledgeVersion } from "../actions";
import { requireUser } from "@/lib/auth";
import { can } from "@/lib/rbac";
import { listTenantAuditLogs, listTenantKnowledge, listTenantUsers, readDatabase } from "@/lib/store";
import { roles } from "@/lib/domain";

const input = (name: string, label: string, value: string, type = "text") => <div className="field"><label htmlFor={name}>{label}</label><input id={name} name={name} type={type} defaultValue={value} required /></div>;

export default async function AdminPage({ searchParams }: { searchParams: Promise<{ tenant?: string }> }) {
  const actor = await requireUser(); const database = await readDatabase(); const requested = (await searchParams).tenant;
  const tenant = actor.role === "SUPER_ADMIN" ? database.tenants.find((item) => item.id === requested) ?? database.tenants[0] : database.tenants.find((item) => item.id === actor.tenantId);
  const users = tenant ? await listTenantUsers(tenant.id) : []; const audits = tenant ? await listTenantAuditLogs(tenant.id) : []; const knowledge = tenant ? await listTenantKnowledge(tenant.id) : [];
  return <main className="admin-shell" style={tenant ? { "--color-primary": tenant.theme.primary } as React.CSSProperties : undefined}><aside className="sidebar"><h2>ResolveOps</h2><a href="#overview">Overview</a><a href="#settings">Tenant settings</a><a href="#brand">Brand & theme</a><a href="#knowledge">Knowledge base</a><a href="#users">People & roles</a><a href="#audit">Audit trail</a></aside><section className="content"><header className="topbar"><div><span className="eyebrow">ADMIN CONTROL CENTRE</span><h1>{tenant?.name ?? "Platform"}</h1></div><form action={logout}><button>Sign out</button></form></header>
  {actor.role === "SUPER_ADMIN" && <section className="panel"><h3>Create tenant</h3><form action={createTenant} className="form-grid">{input("name","Organization name","")}{input("slug","Tenant URL slug","")}<button className="primary wide">Create tenant</button></form></section>}
  {tenant && <><section id="overview" className="stats"><article className="stat"><span className="muted">Active users</span><b>{users.filter((u)=>u.status==="ACTIVE").length}</b></article><article className="stat"><span className="muted">Enabled languages</span><b>{tenant.settings.enabledLanguages.length}</b></article><article className="stat"><span className="muted">Confidence floor</span><b>{Math.round(tenant.settings.confidenceThreshold*100)}%</b></article><article className="stat"><span className="muted">Audited changes</span><b>{audits.length}</b></article></section><div className="grid-two">
  {can(actor.role,"settings:manage") && <><section id="settings" className="panel"><h3>Support behavior</h3><form action={updateSettings}><input type="hidden" name="tenantId" value={tenant.id}/>{input("timezone","Timezone",tenant.settings.timezone)}<div className="field"><label>Default language</label><select name="defaultLanguage" defaultValue={tenant.settings.defaultLanguage}><option value="en">English</option><option value="hi">Hindi</option><option value="hinglish">Hinglish</option></select></div><div className="field"><label>Enabled languages</label><label><input type="checkbox" name="enabledLanguages" value="en" defaultChecked={tenant.settings.enabledLanguages.includes("en")}/> English</label><label><input type="checkbox" name="enabledLanguages" value="hi" defaultChecked={tenant.settings.enabledLanguages.includes("hi")}/> Hindi</label><label><input type="checkbox" name="enabledLanguages" value="hinglish" defaultChecked={tenant.settings.enabledLanguages.includes("hinglish")}/> Hinglish</label></div>{input("requiredSupportFields","Required fields (comma separated)",tenant.settings.requiredSupportFields.join(", "))}{input("confidenceThreshold","AI confidence threshold",String(tenant.settings.confidenceThreshold),"number")}<div className="field"><label>Escalation behavior</label><select name="escalationBehavior" defaultValue={tenant.settings.escalationBehavior}><option value="always">Always</option><option value="outside-hours">Outside hours</option><option value="safety-and-low-confidence">Safety and low confidence</option></select></div><button className="primary">Save support settings</button></form></section>
  <section id="brand" className="panel"><h3>Brand identity</h3><form action={updateBranding}><input type="hidden" name="tenantId" value={tenant.id}/>{input("productDisplayName","Product display name",tenant.branding.productDisplayName)}{input("companyDisplayName","Company display name",tenant.branding.companyDisplayName)}{input("supportAgentName","Support agent name",tenant.branding.supportAgentName)}{input("logoUrl","Logo URL",tenant.branding.logoUrl)}{input("faviconUrl","Favicon URL",tenant.branding.faviconUrl)}{input("footerText","Footer text",tenant.branding.footerText)}{input("supportEmail","Support email",tenant.branding.supportEmail,"email")}{input("supportPhone","Support phone",tenant.branding.supportPhone)}{input("privacyPolicyUrl","Privacy policy URL",tenant.branding.privacyPolicyUrl)}{input("termsUrl","Terms URL",tenant.branding.termsUrl)}<label><input type="checkbox" name="hidePlatformBranding" defaultChecked={tenant.branding.hidePlatformBranding}/> Hide platform branding</label><br/><br/><button className="primary">Save brand</button></form></section>
  <section className="panel"><h3>Runtime theme</h3><form action={updateTheme} className="form-grid"><input type="hidden" name="tenantId" value={tenant.id}/><div className="field"><label>Theme mode</label><select name="mode" defaultValue={tenant.theme.mode}><option>light</option><option>dark</option><option>system</option></select></div>{["primary","secondary","accent","background","surface","text","mutedText","border"].map((key)=><div className="field" key={key}><label>{key}</label><div className="color-field"><input type="color" name={key} defaultValue={tenant.theme[key as keyof typeof tenant.theme] as string}/><span>{tenant.theme[key as keyof typeof tenant.theme]}</span></div></div>)}<div className="field"><label>Radius</label><select name="radius" defaultValue={tenant.theme.radius}>{["none","small","medium","large","rounded"].map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label>Font</label><select name="fontFamily" defaultValue={tenant.theme.fontFamily}>{["Inter","Arial","Georgia","system-ui"].map(x=><option key={x}>{x}</option>)}</select></div><button className="primary wide">Apply theme</button></form></section></>}
  {can(actor.role,"knowledge:manage") && <section id="knowledge" className="panel"><h3>Approved knowledge</h3><p className="muted">Only an approved active version can be retrieved by live support.</p><form action={uploadKnowledgeDocument} className="form-grid"><input type="hidden" name="tenantId" value={tenant.id}/>{input("title","Document title","")}{input("tags","Tags (comma separated)","")}{input("description","Description","")}<div className="field"><label>PDF, DOCX, TXT, MD or HTML</label><input type="file" name="file" accept=".pdf,.docx,.txt,.md,.html" required/></div><button className="primary wide">Upload as draft</button></form>{knowledge.map(({document,versions})=><article className="knowledge-row" key={document.id}><div><b>{document.title}</b><span className={`knowledge-status ${document.status.toLowerCase()}`}>{document.status}</span><small>{versions.length} version{versions.length===1?"":"s"} · {document.tags.join(", ")||"No tags"}</small></div><div className="knowledge-actions">{versions.filter(version=>version.status==="DRAFT").map(version=><form action={approveKnowledgeVersion} key={version.id}><input type="hidden" name="versionId" value={version.id}/><button>Approve v{version.version}</button></form>)}{document.status!=="ARCHIVED"&&<form action={archiveKnowledgeDocument}><input type="hidden" name="documentId" value={document.id}/><button>Archive</button></form>}</div>{document.status!=="ARCHIVED"&&<form action={uploadKnowledgeVersion} className="version-upload"><input type="hidden" name="documentId" value={document.id}/><input type="file" name="file" accept=".pdf,.docx,.txt,.md,.html" required/><button>Upload new version</button></form>}</article>)}</section>}
  {can(actor.role,"users:manage") && <section id="users" className="panel"><h3>People & roles</h3><form action={addUser} className="form-grid"><input type="hidden" name="tenantId" value={tenant.id}/>{input("name","Name","")}{input("email","Email","","email")}{input("password","Temporary password","","password")}<div className="field"><label>Role</label><select name="role">{roles.filter(r=>r!=="SUPER_ADMIN").map(r=><option key={r}>{r}</option>)}</select></div><button className="primary wide">Add user</button></form>{users.map(user=><div className="user-row" key={user.id}><span><b>{user.name}</b><br/><span className="muted">{user.email} · {user.role}</span></span>{user.status === "ACTIVE" && user.id!==actor.id && <form action={deactivateUser}><input type="hidden" name="userId" value={user.id}/><button>Deactivate</button></form>}</div>)}</section>}
  {can(actor.role,"audit:read") && <section id="audit" className="panel"><h3>Read-only audit trail</h3>{audits.slice(0,10).map(item=><div className="audit-row" key={item.id}><span><b>{item.action}</b><br/><span className="muted">{item.entityType} · {item.actorUserId}</span></span><time>{new Date(item.createdAt).toLocaleString()}</time></div>)}</section>}
  </div></>}</section></main>;
}
